### ISSUE TITLE
Research Machine selection when scaling down a MachineSet 

### ISSUE THREAD

**Issue by russellb** [metal3-io/cluster-api-provider-baremetal#10]
When a MachineSet is scaled down, we may have additional criteria to help chose which Machine is the most appropriate one to Delete.  We should determine what the current logic is, and if we should introduce some additional functionality where we can influence which Machine is chosen.

**Comment by mhrivnak** [comment]
This PR merged, which adds the ability to annotate a machine to signify that it's the one you want to delete.

https://github.com/kubernetes-sigs/cluster-api/pull/726

**Comment by russellb** [comment]
We still need to update our cluster-api fork to include that change

**Comment by russellb** [comment]
merged cluster-api-update PR

**Comment by russellb** [comment]
note the key bit about selecting a Machine for deletion when scaling down a MachineSet:

```
Simple delete policy has been modified to select a Machine for scale down with the annotation machineset.clusters.k8s.io/delete-me=yes.
```
