### ISSUE TITLE
Add support for cluster-api v1alpha2

### ISSUE THREAD

**Issue by russellb** [metal3-io/cluster-api-provider-baremetal#101]
The current code only supports the Machine interface of the v1alpha1 API.  At some point we should create a branch to maintain the v1alpha1 code, and evolve master to support the work happening in cluster-api for v1alpha2.

Quoting https://discuss.kubernetes.io/t/the-actuator-interfaces-have-gone-in-the-latest-source-code/7360/2

> Hi, there are no interfaces for providers to implement any more. Instead, providers implement full, regular controllers that watch provider-specific custom resources. We have an open PR to describe the differences between v1alpha1 and v1alpha2 - please see https://github.com/kubernetes-sigs/cluster-api/pull/1211. Also take a look at https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20190610-machine-states-preboot-bootstrapping.md for more details on some of the design changes coming in v1alpha2.

**Comment by russellb** [comment]
https://discuss.kubernetes.io/t/announce-cluster-api-v1alpha2-released/7821

**Comment by Arvinderpal** [comment]
@russellb I can take this task.
I have been going through bootstrap-provider-kubeadm and the provider-docker the last couple of weeks. I also added dual-stack support to kubeadm recently, so have a good understanding of the code base there.

**Comment by russellb** [comment]
Sounds great, thank you!!

**Comment by Arvinderpal** [comment]
Design Doc: https://docs.google.com/document/d/1BY6ZhOEtDz9vd_RBfHamYJYspQhZXtsIE-gQltoayuE/edit?usp=sharing

**Comment by maelk** [comment]
On-going work : https://github.com/Nordix/cluster-api-provider-baremetal/tree/v1alpha2

**Comment by russellb** [comment]
> On-going work : https://github.com/Nordix/cluster-api-provider-baremetal/tree/v1alpha2

This is all being merged into the v1alpha2 branch of this repo now, right?

**Comment by maelk** [comment]
yes, now all work is being merged in the v1alpha2 branch here

**Comment by maelk** [comment]
V1alpha2 was merged into master, I guess we can close this ?

**Comment by russellb** [comment]
yep!  we can close this.
