### ISSUE TITLE
Cloud-init handling in v1alpha2

### ISSUE THREAD

**Issue by maelk** [metal3-io/cluster-api-provider-baremetal#107]
This issue is related to #101. 
Since we are working with physical nodes, we might have node-specific configuration (for example networking). This configuration is tightly tied to the physical node. However, the cloud-init configuration in v1alpha2 is coming from CABPK, hence the possible need for a reconciliation between the content generated by CABPK and the additional configuration related to the node itself, or to the setup of the control-plane load-balancer.
A possibility is to create an additional field containing the user configuration in BaremetalHost and merge its content with the cloud-init generated by CABPK in the CAPI-provider-baremetal controller to generate the final cloud-init to populate the userdata field in the BaremetalHost before provisioning.
We will submit a design document for discussion.

**Comment by maelk** [comment]
Here is a first draft document [WIP] : https://docs.google.com/document/d/1utLPR2LQh6CnAEkLbKNaPlaYrygplrHzcLBXg3MiBkk

**Comment by hardys** [comment]
@maelk thanks for the proposal - do you want to enable comments there or shall we discuss here in the issue?

I have some questions about how we can make this work not only for cloud-init, but also for those of us using alternative first-boot configuration tools e.g ignition or others - we need to avoid baking assumptions about the tool into the BMH interfaces IMO.

Relatedly, two points from the doc:

> Validate the user-provided cloud-config (to prevent conflict with CABPK output)

I think we need more details here, how will we validate?  Are conflicting keys allowed?  Where tools support specific strategies for merging config values, how do we consider that in the validation?

> Merge the inputs from CABPK and user

This is harder than it sounds IME :)

Cloud-init has specific interfaces to control how various types get merged:

https://cloudinit.readthedocs.io/en/latest/topics/merging.html

And ignition has something similar, where you can choose to either to either merge or replace an existing config:

https://github.com/coreos/ignition/blob/master/doc/configuration-v3_0.md

I wonder if we make use of the existing merge capabilities in cloud-init (and ignition) and just append any per-host data, then let the tools take care of any merging?  This would also mean it's up to the users to specify any `merge_how` directives etc.

**Comment by maelk** [comment]
@hardys The commenting is enabled for all members of metal3-dev google group. I would propose to discuss everything on the document.
About your points, we're looking into how we could do that. We definitely would want to support more tools. About the validation, we have now in mind a very simple model that would trigger a failure if there are conflicts. And about the merging, we could use the capabilities from cloud-init, however that would not give us the fine-grained control and the possibility to define a part of the user input to be run before CABPK output and after it. We're investigating and will update the document with our findings
