### ISSUE TITLE
LeaderElectionID should be unique

### ISSUE THREAD

**Issue by noamran** [metal3-io/cluster-api-provider-baremetal#113]
This issue was reported in other providers - Running several Cluster API pods (e.g. CAPI + CABPK + an infra provider) in the same namespace results in leader election errors. 
More details here - kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#271

**Comment by zaneb** [comment]
CAPBM [passes](https://github.com/metal3-io/cluster-api-provider-baremetal/blob/master/cmd/manager/main.go#L64-L66) `LeaderElection: false`, so I don't think there's anything to do here?

**Comment by mhrivnak** [comment]
I think that's just an oversight. CAPBM should be using leader election. It ensures a safe transition whenever the controller gets upgraded, rescheduled to a different node, or restarted for any reason. I'm not aware of any downsides.

**Comment by zaneb** [comment]
Fixed in master by #144.

I've also proposed a PR to the OpenShift fork (the only v1alpha1-based branch): openshift/cluster-api-provider-baremetal#55.

/close
