### ISSUE TITLE
[v1alpha2] Pivoting to target cluster

### ISSUE THREAD

**Issue by kashifest** [metal3-io/cluster-api-provider-baremetal#209]
Once target cluster's controlplane is up and running, we should pivot the source cluster provider components (controllers, CRDs, CRs ) , CAPI objects, BMH etc to the target cluster so as to make the target cluster independent and autonomous for the rest of its life-cycle and make the ephimeral/bootstrap cluster node free. We should look into the pivoting carefully in baremetal scenario since we have extra objects to pivot (BMH, secrets) and also we need to keep the status of few of the cluster components.

**Comment by kashifest** [comment]
me and @Xenwar  are looking into this currently. 
/assign @kashifest 
/assign @Xenwar

**Comment by dhellmann** [comment]
I'm going to close this because I think we've moved on from v1alpha2 to v1alpha3. If you are still working on this, that's ok. Please propose patches in cluster-api-provider-metal3 for the newer API.
