### ISSUE TITLE
Do we have plan to create "Operator"

### ISSUE THREAD

**Issue by vincent-pli** [metal3-io/cluster-api-provider-baremetal#217]
Do we have plan to create `Operator` to prepare bare metal cluster api environment ?

**Comment by russellb** [comment]
Nobody is working on right now that I know of.

There's an openshift specific operator that deploys the cluster-api provider and the baremetal-operator.  The baremetal-operator piece may be a useful reference.  Most of the rest of the component is openshift specific, though.

https://github.com/openshift/machine-api-operator/blob/master/pkg/operator/baremetal_pod.go

**Comment by stbenjam** [comment]
There's currently no plans for an operator, the preferred deployment mechanism is using the deployment yamls in the config/ directory.

/close
