### ISSUE TITLE
Another "works on x86_64 only"-project

### ISSUE THREAD

**Issue by c5253458** [metal3-io/cluster-api-provider-baremetal#228]

**Comment by russellb** [comment]
Did you have any more details you wanted to add?  An issue with no description is not particularly helpful.

**Comment by russellb** [comment]
Based on seeing other duplicate issues on other repositories, such as https://github.com/code-ready/crc/issues/957, it looks like this is being opened by a script or something.  Feel free to reopen if you have more information or suggestions to provide.

**Comment by c5253458** [comment]
The effort is the same for every open source project that should run on different platforms and does CI/CD

OSU Open Source Lab provides free direct access to the hardware platforms as well as jenkins Continuous Integration:

* [IBM Z Development Hosting](https://osuosl.org/services/ibm-z/)
* [POWER Development Hosting](https://osuosl.org/services/powerdev/)

Does that satisfy your project's requirements ?
