### ISSUE TITLE
Should we rename Metal3 provider ?

### ISSUE THREAD

**Issue by maelk** [metal3-io/cluster-api-provider-baremetal#267]
In the cluster API office hour, it was requested to change the name of this provider, as baremetal is confusing. Renaming it on CAPI side is rather trivial, as it is mostly documentation. However, should this change be propagated deeper, specifically in this repository, inc. the repo name, metal3-docs and the website (try-it.md in particular), quay.io images etc. ?

A first step could be to list all places where we use the CAPBM name and then decide to which level we should perform the change.

**Comment by maelk** [comment]
For alternative name, what about Cluster API Provider Metal3 -> CAPM3 ?

**Comment by russellb** [comment]
What’s confusing about it? Confusing with other possible ways to use cluster API with bare metal?

**Comment by maelk** [comment]
Yes, they are talking of a possible other provider, Tinkerbell that also does baremetal. So they want to separate the different baremetal providers

**Comment by russellb** [comment]
Is anyone already working on that? Seems like the baremetal-operator would be one possible integration point.

**Comment by maelk** [comment]
Not that I know. The CAPI issue is here : https://github.com/kubernetes-sigs/cluster-api/issues/2447

**Comment by maelk** [comment]
As I pointed there, if we want to rename the CRDs, it would be better to do it before v1alpha3 is out, to break the backwards compatibility now rather than later.

**Comment by maelk** [comment]
Here are the different points that needs to be tackled related to a name change:

- Docs change in CAPI (done in PR https://github.com/kubernetes-sigs/cluster-api/pull/2462)
- Docs change in CAPBM (done in PR)
- Deployment change, namespace and prefixes (done in PR)
- removing of capbm reference in code (done in PR)
- Renaming CRDs and change in code, ⚠️ Breaking backwards compatibility
- renaming repo
- renaming images

The PR is doing mostly cosmetic changes to stay in line with CAPI. The remaining core questions are : 

- Do we rename the repo and the images ? What would be the impact of renaming the repo ?
- Do we rename the CRDs and break the backwards compatibility ? 

Let's apply a lazy consensus on this by Wednesday 04th Community meeting. If no comments against it, we'll keep the CRDs as is to not break the compatibility, but rename the image and the repo if no blockers is found by then.

**Comment by maelk** [comment]
The following PRs are doing the changes for the points 2, 3 and 4:

- CAPM3: https://github.com/metal3-io/cluster-api-provider-baremetal/pull/268
- metal3-dev-env: https://github.com/metal3-io/metal3-dev-env/pull/239
- project-infra: https://github.com/metal3-io/project-infra/pull/57 
- website docs: https://github.com/metal3-io/metal3-io.github.io/pull/153
