### ISSUE TITLE
actuator sets config drive secret on BareMetalHost

### ISSUE THREAD

**Issue by mhrivnak** [metal3-io/cluster-api-provider-baremetal#31]
A "config drive" Secret will be present in the cluster, and it will contain data that the BareMetalHost needs in order to configure a provisioned host. For now the secret reference is always the same, so it can be hard-coded. In the future the data may be read from the Machine's provider spec.

This task is to ensure the actuator writes the values to corresponding fields on the BareMetalHost.

As an example, currently in openshift the secret that contains worker config data is showing up with this identity:

```
  name: worker-user-data
  namespace: openshift-machine-api
```

**Comment by dhellmann** [comment]
https://github.com/metalkube/metalkube-docs/blob/master/design/worker-config-drive.md has some additional details
