### ISSUE TITLE
Add addresses to Machine

### ISSUE THREAD

**Issue by russellb** [metal3-io/cluster-api-provider-baremetal#49]
We need to populate the addresses field of Machines.

The contents must match what shows up in the associated Node, but the information must come from elsewhere, as it's needed sooner.

This has a dependency on the baremetal-operator completing integration of host introspection.  The host introspection data will contain IP and hostname information that we can then copy into the Machine.

**Comment by russellb** [comment]
This depends on https://github.com/metalkube/baremetal-operator/pull/147

**Comment by russellb** [comment]
This was mostly implemented by https://github.com/metal3-io/cluster-api-provider-baremetal/pull/24

but a Node will also have the hostname, and we don't have that implemented yet.

There's a related RFE about the hostname here: https://github.com/metal3-io/baremetal-operator/issues/190

**Comment by russellb** [comment]
@bcrochet Are you working on the hostname part of this, too?

**Comment by bcrochet** [comment]
> @bcrochet Are you working on the hostname part of this, too?

I can. I'll take a look at the rfe.

**Comment by bcrochet** [comment]
Implemented by metal3-io/baremetal-operator#213 and #91
