### ISSUE TITLE
actuator needs to wait for host to be deprovisioned before returning from Delete()

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/cluster-api-provider-baremetal#84]
In order to correctly fence hosts, we need to ensure that the Machine objects are not deleted until the host has been wiped, powered off, or both -- so that it is no longer trying to be a node.

It should be able to determine that the host is wiped by watching for its Status.Provisioning.Image field to have an empty image.

Today, the Machine controller appears to support returning a special type of error to indicate that a Machine needs to be requeued [1]. That works differently in the OpenShift version of the controller code [2], though, so we either need to update the copy of the cluster-api code used there or do something else.

[1] https://github.com/metal3-io/cluster-api-provider-baremetal/blob/master/vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/controller.go#L172
[2] https://github.com/openshift/cluster-api-provider-baremetal/blob/master/vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go#L206

**Comment by beekhof** [comment]
Looks like the difference came about as part of upstreams move to kubebuilder ( https://github.com/kubernetes-sigs/cluster-api/commit/80129c0ca4eee12c47be0c04ea551fdd6f2cbaba ), that may have something to do with why we didnt pick it up.

In the end, as long as the actuator returns an error until the node is off, then in end it works out much the same. The Machine Health Check code will retry the machine deletion in its own reconcile loop.

/cc @ondrejmular

**Comment by dhellmann** [comment]
I think I would prefer to bring in whatever changes are needed to support the special error return type instead of logging errors for several minutes while we reboot and clean the host.

**Comment by zaneb** [comment]
The difference is only refactoring out of the code from [1] into a separate function in [2]:
https://github.com/openshift/cluster-api-provider-baremetal/blob/master/vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go#L343-L350
The refactoring was pulled in with the last update here:
https://github.com/openshift/cluster-api-provider-baremetal/commit/72e935259ef1d5190e3254bff3b7ebdd9111e46b#diff-85a5a781b3bae61d434d5127ae120b16R206

It appears to me that in either case returning an error of type `*controllerError.RequeueAfterError` will do the Right Thing.

**Comment by mhrivnak** [comment]
I agree with that assessment. I concluded the same in an email thread
recently but neglected to add that here.
