### ISSUE TITLE
Unable to setup dev environment for cluster-api

### ISSUE THREAD

**Issue by prankul88** [metal3-io/cluster-api-provider-baremetal#85]
My aim is to setup development environment for cluster api using baremetal provider. I am using minikube for this.

Following link [https://github.com/metal3-io/cluster-api-provider-baremetal/blob/master/docs/dev/minikube.md](url)

**What I did**
1. kubectl apply -k vendor/sigs.k8s.io/cluster-api/config/crds/
2. kubectl apply -f vendor/github.com/metal3-io/baremetal-operator/deploy/crds/metal3_v1alpha1_baremetalhost_crd.yaml
3. Followed all the steps for creation of baremetal host [https://github.com/metal3-io/baremetal-operator/blob/master/docs/dev-setup.md](url)

But following this link I am stuck at command `operator-sdk up local --namespace=metal3
`

> INFO[0000] Running the operator locally.                
INFO[0000] Using namespace metal3.                      
{"level":"info","ts":1560334189.93631,"logger":"cmd","msg":"Go Version: go1.12.5"}
{"level":"info","ts":1560334189.9363344,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1560334189.9363453,"logger":"cmd","msg":"Version of operator-sdk: v0.4.0+git"}
{"level":"info","ts":1560334189.9372797,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1560334189.9372985,"logger":"leader","msg":"Skipping leader election; not running in a cluster."}
{"level":"info","ts":1560334189.9877634,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1560334189.9880195,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"metal3-baremetalhost-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1560334189.9881308,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"metal3-baremetalhost-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1560334189.9882035,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1560334190.0884702,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"metal3-baremetalhost-controller"}
{"level":"info","ts":1560334190.1887379,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"metal3-baremetalhost-controller","worker count":1}

![Screenshot from 2019-06-12 22-04-47](https://user-images.githubusercontent.com/40868849/59369662-83409200-8d5e-11e9-8fa1-50a2cd17c897.png)

After waiting for half an hour, I am still seeing this
Would be very helpful if someone could help me understand what can be done to overcome this issue.

**Comment by dhellmann** [comment]
I think things are working as expected.

Running that operator-sdk command launches the operator in a process on your local host, and it blocks until the process exits. You can use another terminal to create host resources, and then you will see more log output in the window running the operator.

**Comment by prankul88** [comment]
Thank you @dhellmann . Your feedback helped me clear a lot of confusion.
Now that I have baremetal host process running in my system, I am trying to setup a cluster using 

`./clusterctl create cluster --provider <provider> --bootstrap-type <bootstrap-type> -c cluster.yaml \
  -m machines.yaml -p provider-components.yaml -a addons.yaml` [https://github.com/kubernetes-sigs/cluster-api/tree/master/cmd/clusterctl#creating-a-cluster](url)

But unlike other cloud providers which all have these yaml available at their respective repos, I am unable to find these for baremetal provider.
I have just started here so don't have much idea. Any suggestions would be very helpful.

**Comment by dhellmann** [comment]
metal3 only supports the Machine portion of the cluster API so far. We're working on support for components higher up the stack, but right now I anticipate that support waiting for newer versions of those APIs that decouple more of the work from the individual providers, so we can take advantage of more shared implementation work. Because of this limitation, I would not expect metal3 to work with clusterctl for a while longer.

Our https://github.com/metal3-io/metal3-dev-env repo will let you build a cluster using minikube and then you can add bare metal workers to that by registering them as hosts. This is obviously not a production-ready configuration. :-)

**Comment by russellb** [comment]
@prankul88 Does metal3-dev-env work for you?  Are there any more issues we need to clear up on this issue?  Thanks!

**Comment by prankul88** [comment]
> Does metal3-dev-env work for you? Are there any more issues we need to clear up on this issue? Thanks!

@russellb I did not actually. But the original issue reported is resolved. So I am closing this issue.
