### ISSUE TITLE
Machine deletion is broken

### ISSUE THREAD

**Issue by russellb** [metal3-io/cluster-api-provider-baremetal#95]
PR #86 changed the behavior of machine deletion.  The intention was to have the machine actuator delay Machine deletion until the BareMetalHost was deprovisioned.

It does this by first clearing the image field on the BareMetalHost and then watching BMH host status until it later will clear the ConsumerRef field.  

The problem with this approach is that the baremetal-operator treats a BMH with a ConsumerRef field set but no image as an "externally provisioned" host.  As a result, machine deletion can never finish, as a deleted machine turns the BMH into an "externally provisioned" host.

See https://github.com/metal3-io/metal3-dev-env/issues/26 for where this problem was originally reported.

**Comment by dhellmann** [comment]
I think we need 2 fixes for this. First, the actuator here should handle the externally provisioned case directly to allow deleting host objects associated with control plane nodes. Second, the baremetal operator should not treat a host that has ever had an image provisioned as externally provisioned, even if it doesn't have an image right now. That better supports the deprovision-on-delete use case.

**Comment by zaneb** [comment]
I tried reverting only the patch that causes the Machine to hang on to Host via the consumerRef until deletion is complete (54df54afda5b7cd2ca21dcbdee0314d31d6c70a4), but this results in the new Machine object that is created immediately grabbing the consumerRef and setting the same image details, so the Host never gets deprovisioned. There doesn't appear to be any short-term fix here that wouldn't reintroduce #84. The only long-term fix is to resolve metal3-io/baremetal-operator#238 to not go into the "externally provisioned" state.

**Comment by dhellmann** [comment]
See https://github.com/metal3-io/baremetal-operator/pull/250
